import { type Location } from '../../src/types';

export const locations: Location[] = [
  {
    _id: '1',
    title: 'United States',
    desc: 'Programs across multiple states supporting local giving initiatives.',
    slug: 'united-states',
    location: { iso: 'US', region: '', coordinates: [-95.7129, 37.0902] },
  },
  {
    _id: '2',
    title: 'United Kingdom',
    desc: 'Community fundraising campaigns across England, Scotland and Wales.',
    slug: 'united-kingdom',
    location: { iso: 'GB', region: '', coordinates: [-3.4359, 55.3781] },
  },
  {
    _id: '3a',
    title: 'Toronto Community Foundation',
    desc: 'Annual giving campaign supporting shelters and food banks across the GTA.',
    slug: 'toronto-community-foundation',
    location: { iso: 'CA', region: 'CA-ON', coordinates: [-79.3832, 43.6532] },
  },
  {
    _id: '3b',
    title: 'Montreal Giving Circle',
    desc: 'Francophone-led fundraising collective partnering with local nonprofits.',
    slug: 'montreal-giving-circle',
    location: { iso: 'CA', region: 'CA-QC', coordinates: [-73.5673, 45.5017] },
  },
  {
    _id: '3c',
    title: 'Vancouver Island Relief Fund',
    desc: 'Disaster preparedness and community resilience initiatives.',
    slug: 'vancouver-island-relief-fund',
    location: { iso: 'CA', region: 'CA-BC', coordinates: [-123.1216, 49.2827] },
  },
  {
    _id: '3d',
    title: 'Calgary Youth Giving Network',
    desc: 'Youth-led campaigns raising funds for mental health programmes.',
    slug: 'calgary-youth-giving-network',
    location: { iso: 'CA', region: 'CA-AB', coordinates: [-114.0719, 51.0447] },
  },
  {
    _id: '3e',
    title: 'Halifax Harbour Fund',
    desc: 'Maritime community supporting ocean conservation and local fisheries.',
    slug: 'halifax-harbour-fund',
    location: { iso: 'CA', region: 'CA-NS', coordinates: [-63.5752, 44.6488] },
  },
  {
    _id: '3f',
    title: 'Winnipeg Prairie Initiative',
    desc: 'Grassroots giving movement focused on Indigenous community support.',
    slug: 'winnipeg-prairie-initiative',
    location: { iso: 'CA', region: 'CA-MB', coordinates: [-97.1384, 49.8951] },
  },
  {
    _id: '3g',
    title: 'Saskatchewan Rural Aid',
    desc: 'Agricultural community fundraising for rural healthcare access.',
    slug: 'saskatchewan-rural-aid',
    location: { iso: 'CA', region: 'CA-SK', coordinates: [-104.6189, 50.4452] },
  },
  {
    _id: '3h',
    title: 'Ottawa National Giving Day',
    desc: 'Capital region campaign coordinating federal and local charity drives.',
    slug: 'ottawa-national-giving-day',
    location: { iso: 'CA', region: 'CA-ON', coordinates: [-75.6972, 45.4215] },
  },
  {
    _id: '3i',
    title: "St. John's Newfoundland Fund",
    desc: 'East coast giving initiative supporting remote community services.',
    slug: 'st-johns-newfoundland-fund',
    location: { iso: 'CA', region: 'CA-NL', coordinates: [-52.7126, 47.5615] },
  },
  {
    _id: '3j',
    title: 'Whitehorse Northern Network',
    desc: 'Northern communities fundraising for winter emergency preparedness.',
    slug: 'whitehorse-northern-network',
    location: { iso: 'CA', region: 'CA-YT', coordinates: [-135.0568, 60.7212] },
  },
  {
    _id: '3k',
    title: 'Yellowknife Arctic Fund',
    desc: 'Supporting education and housing initiatives in the Northwest Territories.',
    slug: 'yellowknife-arctic-fund',
    location: { iso: 'CA', region: 'CA-NT', coordinates: [-114.3718, 62.454] },
  },
  {
    _id: '3l',
    title: 'New Brunswick Community Collective',
    desc: 'Bilingual giving campaigns across Fredericton and Moncton.',
    slug: 'new-brunswick-community-collective',
    location: { iso: 'CA', region: 'CA-NB', coordinates: [-66.6431, 46.5653] },
  },
  {
    _id: '4',
    title: 'Brazil',
    desc: 'Grassroots giving movement growing across São Paulo and Rio de Janeiro.',
    slug: 'brazil',
    location: { iso: 'BR', region: '', coordinates: [-51.9253, -14.235] },
  },
  {
    _id: '5',
    title: 'Germany',
    desc: '',
    slug: 'germany',
    location: { iso: 'DE', region: '', coordinates: [10.4515, 51.1657] },
  },
  {
    _id: '6',
    title: 'France',
    desc: 'National day of giving coordinated through local nonprofit networks.',
    slug: 'france',
    location: { iso: 'FR', region: '', coordinates: [2.2137, 46.2276] },
  },
  {
    _id: '7',
    title: 'India',
    desc: 'Large-scale campaigns reaching rural and urban communities.',
    slug: 'india',
    location: { iso: 'IN', region: '', coordinates: [78.9629, 20.5937] },
  },
  {
    _id: '8',
    title: 'Kenya',
    desc: '',
    slug: 'kenya',
    location: { iso: 'KE', region: '', coordinates: [37.9062, -0.0236] },
  },
  {
    _id: '9',
    title: 'Australia',
    desc: 'End of year giving campaigns partnering with national charities.',
    slug: 'australia',
    location: { iso: 'AU', region: '', coordinates: [133.7751, -25.2744] },
  },
  {
    _id: '10',
    title: 'Japan',
    desc: '',
    slug: 'japan',
    location: { iso: 'JP', region: '', coordinates: [138.2529, 36.2048] },
  },
  {
    _id: '11',
    title: 'South Africa',
    desc: 'Community-led initiatives focused on education and food security.',
    slug: 'south-africa',
    location: { iso: 'ZA', region: '', coordinates: [22.9375, -30.5595] },
  },
  {
    _id: '12',
    title: 'Mexico',
    desc: '',
    slug: 'mexico',
    location: { iso: 'MX', region: '', coordinates: [-102.5528, 23.6345] },
  },
  {
    _id: '13',
    title: 'Nigeria',
    desc: 'Youth-led fundraising networks expanding across Lagos and Abuja.',
    slug: 'nigeria',
    location: { iso: 'NG', region: '', coordinates: [8.6753, 9.082] },
  },
  {
    _id: '14',
    title: 'Argentina',
    desc: '',
    slug: 'argentina',
    location: { iso: 'AR', region: '', coordinates: [-63.6167, -38.4161] },
  },
  {
    _id: '15',
    title: 'Netherlands',
    desc: 'Collaborative giving campaigns across Amsterdam and Rotterdam.',
    slug: 'netherlands',
    location: { iso: 'NL', region: '', coordinates: [5.2913, 52.1326] },
  },
  {
    _id: '16',
    title: 'Sweden',
    desc: '',
    slug: 'sweden',
    location: { iso: 'SE', region: '', coordinates: [18.6435, 60.1282] },
  },
  {
    _id: '17',
    title: 'Indonesia',
    desc: 'Community fundraising initiatives across Java and Sumatra.',
    slug: 'indonesia',
    location: { iso: 'ID', region: '', coordinates: [113.9213, -0.7893] },
  },
  {
    _id: '18',
    title: 'Colombia',
    desc: '',
    slug: 'colombia',
    location: { iso: 'CO', region: '', coordinates: [-74.2973, 4.5709] },
  },
  {
    _id: '19',
    title: 'Philippines',
    desc: 'Disaster relief and community resilience giving programmes.',
    slug: 'philippines',
    location: { iso: 'PH', region: '', coordinates: [121.774, 12.8797] },
  },
  {
    _id: '20',
    title: 'Poland',
    desc: '',
    slug: 'poland',
    location: { iso: 'PL', region: '', coordinates: [19.1451, 51.9194] },
  },
  {
    _id: '21',
    title: 'Ghana',
    desc: 'Local NGO networks coordinating annual day of giving events.',
    slug: 'ghana',
    location: { iso: 'GH', region: '', coordinates: [-1.0232, 7.9465] },
  },
  {
    _id: '22',
    title: 'New Zealand',
    desc: '',
    slug: 'new-zealand',
    location: { iso: 'NZ', region: '', coordinates: [174.886, -40.9006] },
  },
  {
    _id: '23',
    title: 'Chile',
    desc: 'National campaigns focused on education and environmental causes.',
    slug: 'chile',
    location: { iso: 'CL', region: '', coordinates: [-71.5429, -35.6751] },
  },
  {
    _id: '24',
    title: 'Portugal',
    desc: '',
    slug: 'portugal',
    location: { iso: 'PT', region: '', coordinates: [-8.2245, 39.3999] },
  },
  {
    _id: '25',
    title: 'Bangladesh',
    desc: 'Microgiving initiatives supporting rural development programmes.',
    slug: 'bangladesh',
    location: { iso: 'BD', region: '', coordinates: [90.3563, 23.685] },
  },
];
